# Generated by Django 5.1.2 on 2024-10-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankLoan',
            fields=[
                ('Name', models.CharField(max_length=20)),
                ('MobileNumber', models.IntegerField(primary_key='MobileNumber', serialize=False)),
            ],
        ),
    ]
