# Generated by Django 5.1.2 on 2024-10-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='loan',
            fields=[
                ('Name', models.CharField(max_length=50)),
                ('Accno', models.IntegerField(primary_key='Accno', serialize=False)),
                ('Amount', models.IntegerField()),
                ('Interest', models.FloatField()),
                ('Startdate', models.DateField()),
                ('Phoneno', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Enddate', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='BankLoan',
        ),
    ]
